### ISSUE TITLE
Use 'usethis' package

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcgovr#1]
For functions like`add_code_of_conduct`, `add_contributing` etc., [usethis](https://github.com/r-lib/usethis) likely has more robust implementations than we have - should import **usethis** when it hits CRAN.

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bcgovr::ready for "publicizing"](https://trello.com/c/Nhm40VR1/5-bcgovrready-for-publicizing)

**Comment by boshek** [comment]
Now on CRAN:
https://cran.r-project.org/web/packages/usethis/index.html
