### ISSUE TITLE
Use rstudioapi functions

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcgovr#16]
[rstudioapi v0.7.0](https://cran.r-project.org/web/packages/rstudioapi/index.html) is on CRAN now and has the `initializeProject` and `openProject` functions, which we have [commented out currently](https://github.com/bcgov/bcgovr/blob/master/R/analysis_skeleton.R#L140-L144). I think we can use them now.

**Comment by boshek** [comment]
For `analysis_skeleton` a new rstudio session will open the appropriate directory:

https://github.com/bcgov/bcgovr/blob/b0caface0e8a9166be24fe6d5e6e28a9afd425fb/R/analysis_skeleton.R#L139-L147

For `package_skeleton` only a project is created but rstudio is not opened automatically:

https://github.com/bcgov/bcgovr/blob/b0caface0e8a9166be24fe6d5e6e28a9afd425fb/R/package_skeleton.R#L54-L61

The thinking here is that if a user is using the `package_skeleton()` that type of automated behaviour is less desirable.

**Comment by ateucher** [comment]
Looks great to me! I think we can remove the commented-out code now too...
