### ISSUE TITLE
Make template accessable by RStudio File -> New Project

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcgovr#17]
[rstudioapi](https://cran.r-project.org/web/packages/rstudioapi/index.html) now has the ability to add a [project template](https://rstudio.github.io/rstudio-extensions/rstudio_project_templates.html) to the New Project GUI. Currently only available in the RStudio Preview.

**Comment by ateucher** [comment]
![nov-15-2017 16-42-50_480](https://user-images.githubusercontent.com/2816635/32867825-2de80ee0-ca24-11e7-8e54-154762fc7d76.gif)

**Comment by ateucher** [comment]
@stephhazlitt @boshek

**Comment by boshek** [comment]
Closed by https://github.com/bcgov/bcgovr/issues/17
