### ISSUE TITLE
README.Rmd vs README.md

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcgovr#19]
In `analysis_skeleton()` and `package_skeleton()`, (and further down the stack in `add_readme()`), if the `rmarkdown = TRUE`, then both a `README.md` and `README.Rmd` are added to the directory - Is this necessary, or should just the `.Rmd` be added? @boshek @stephhazlitt

**Comment by ateucher** [comment]
Relevant code here: https://github.com/bcgov/bcgovr/blob/master/R/add_meta.R#L33-L41

**Comment by boshek** [comment]
I think only add the `.Rmd`. I think that was my oversight.

**Comment by ateucher** [comment]
Cool, thanks. I'll fix that.

**Comment by stephhazlitt** [comment]
Agreed. So the default will be a README.md file, and if user adds `rmarkdown=TRUE` the folder will be populated with the README.Rmd only?

**Comment by ateucher** [comment]
I agree with that default for `analysis_skeleton` for sure - how about default `rmarkdown = TRUE` for `package_skeleton`?
