### ISSUE TITLE
New .Rbuildignore that captures all the additional BC gov files that are added

### ISSUE THREAD

**Issue by boshek** [bcgov/bcgovr#2]
Using `package_skeleton()` create many file that aren't automatically added to Rbuildignore. A better template should be added that called with `add_rbuildignore` or something like that.

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bcgovr::ready for "publicizing"](https://trello.com/c/Nhm40VR1/5-bcgovrready-for-publicizing)
