### ISSUE TITLE
Depend more on usethis package, including the create_from_github()

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/bcgovr#26]
I wonder about simplifying `bcgovr` to rely more on the `usethis` package, including a function that both opens a GH repo & clones the repo locally e.g. `usethis::create_from_github`. This is still a friction point for users, in my opinion. I know we are already using some elements of `usethis` under the hood, but I wonder if we could rely more on this maturing rstudio package and strip down `bcgovr` for delivery of only the bcgov-specific set-up tasks?

**Comment by stephhazlitt** [comment]
As we near the completion of implementing this enhancement, I wonder about adding a `create_from_bcgov_github` function? I think many users will open an origin in bcgov GitHub and then move to their machine to start a local?

**Comment by ateucher** [comment]
💯 I think it's the final piece in our current vision

**Comment by stephhazlitt** [comment]
And so we are done.
