### ISSUE TITLE
Add empty tmp etc folders to skeleton

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcgovr#27]
`analysis_skeleton` makes a `tmp` folder that is then added to `.gitignore`, to hold intermediate objects. But if someone else pulls the code and runs it, it errors because the `tmp` folder doesn't exist.

So instead of having `tmp` be in the global `.gitignore`, add the `tmp` folder with a `.gitignore` file inside, that just contains:

```
*
!.gitignore
```

This will enable the folder to be committed, but not its contents.

**Comment by stephhazlitt** [comment]
I think this issue is deprecated with the revised decision on the default directory structure?

```
 dir_struct <- c("out/", "data/",
               "01_load.R", "02_clean.R", "03_analysis.R", "04_output.R", "run_all.R")
```

**Comment by ateucher** [comment]
I think so

**Comment by stephhazlitt** [comment]
Closing issue until the time when we add "tmp/" back into the default directory structure 😆 .
