### ISSUE TITLE
Proper documentation for defunct `devex_badge()` function?

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/bcgovr#40]
We decided to skip deprecation/defunct documentation for the changes in `bcgovr` functions, given that `bcgovr` functionality is fully interactive, or is intended to be. With test driving, I have realized that we have `devex_badge()` scripted in almost _every_ [EnvReportBC repo](https://github.com/bcgov/EnvReportBC). 

Given this, and that perhaps others have used this function in the same way, I suggest we add in either a defunct error message, or keep `devex_badge()` with a deprecation message to now use `insert_bcgov_devex_badge()`?

**Comment by ateucher** [comment]
Oh good idea! I vote for the latter (still works with a deprecation message) to give ourselves a bit of time :)

**Comment by stephhazlitt** [comment]
I like time ⌛!

And still all OK with not adding defunct.R file, or should I just throw one in since we are on the path, and it is best practice and all?

**Comment by stephhazlitt** [comment]
`bcgovr::devex_badge` [works again with deprecation warning](https://github.com/bcgov/bcgovr/commit/d231bf034e24e00aa91fc53119ee322727be7338). After reviewing the rest of the interactive functions&mdash;and :thinking:  about it again&mdash;I don't think the defunct.R approach  is necessary for the remainder of the renamed functions.

**Comment by ateucher** [comment]
Beautiful, thanks!
