### ISSUE TITLE
Using: create_bcgov_project()

### ISSUE THREAD

**Issue by NoushinN** [bcgov/bcgovr#49]
trying to make an existing .Rproj of mine bcgovr-proof: the code in this [repo](https://github.com/bcgov/bcgovr/blob/master/R/create.R) for create_bcgov_projec() gives errors, may I know the dependencies of this repo?

**Comment by ateucher** [comment]
Hi @NoushinN. `bcgovr` is created as an R package, so if you use `remotes::install_github()` to install it, it will take care of the dependencies for you, you don't need to clone the repo directly.

```r
# Make sure you have the remotes package installed:
# install.packages("remotes")

# Install the bcgovr package:
remotes::install_github("bcgov/bcgovr")

# Then load the package, and call the function:
library(bcgovr)
create_bcgov_project("path_to_you_project")
```

I hope that helps.

**Comment by NoushinN** [comment]
Thank you @ateucher , this worked well for one project but here's a new error I am getting, any clues?
![image](https://user-images.githubusercontent.com/37668936/55457017-7ef93b00-559d-11e9-87d5-0e0575807a16.png)

**Comment by ateucher** [comment]
Hi @NoushinN - that's a strange one. Can you try loading `bcgovr` first (i.e., `library(bcgovr)`, then copy and paste the output of `sessionInfo()` here? It seems like you don't have the `usethis` package installed... but bcgovr should install it automatically.

**Comment by NoushinN** [comment]
it's definitely a new error @ateucher : here's the session info after loading the bcgovr library: 
![image](https://user-images.githubusercontent.com/37668936/55497350-0bcfe300-55f6-11e9-8562-636c7a2f268c.png)

**Comment by ateucher** [comment]
Can you please paste the text of the output rather than a screenshot?

**Comment by NoushinN** [comment]
Sure, this?

> library(bcgovr)
> library(reprex)
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reprex_0.2.1 bcgovr_1.0.3

loaded via a namespace (and not attached):
[1] compiler_3.5.3 tools_3.5.3    fs_1.2.7       rstudioapi_0.7 yaml_2.2.0     Rcpp_1.0.1     rlang_0.3.3

**Comment by NoushinN** [comment]
@ateucher it's working now after two restarts! I do not know why honestly, thank you very much for looking!

**Comment by ateucher** [comment]
Gremlins apparently! Thanks @NoushinN :)
