### ISSUE TITLE
Consider changing default for Rmd README?

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/bcgovr#69]
This default behaviour has been discussed before, however opening again for consideration. 

_Why again now?_ I have seen a number of unrendered `Rmd` READMEs in bcgov repos setup with {bcgovr}. IMO most users expect or only need the `.md` README out of the box, especially novice users of the package, so wonder if this should be the default? And then require a user to set `rmarkdown = TRUE` manually if that approach is needed?

e.g., https://github.com/bcgov/bcgovr/blob/master/R/create.R#L42

**Comment by ateucher** [comment]
I think this makes sense. Good idea to default to the easiest for the novice user, knowing that an advanced user will easily know how to change it to suit their needs

**Comment by boshek** [comment]
Also because this code is probably exclusively used interactively, it doesn't feel like there would be many breaking changes.

**Comment by henry-ngo** [comment]
Pinging @reikookamoto for user feedback, since she most recently used these functions on our team.

**Comment by stephhazlitt** [comment]
Would we want the same default behaviour for `create_bcgov_package()`? I think so for consistency, however wonder if packages ever _just_ have a `README.md`?

**Comment by ateucher** [comment]
I'd be tempted to have `Rmd` as default for packages; I feel like it is a different user base, so maybe the novice argument doesn't apply?

**Comment by reikookamoto** [comment]
Oops - I just saw that I got tagged in this thread. Nice to see that the changes already got implemented!

**Comment by stephhazlitt** [comment]
Closed with https://github.com/bcgov/bcgovr/pull/70.
