### ISSUE TITLE
Update R-CMD-Check badge url to reflect GHAction

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/bcgovr#74]
See `bcdata` or `bcmaps` yaml for examples.

**Comment by boshek** [comment]
Hmm... is this not working currently? 
https://github.com/bcgov/bcgovr/blob/master/.github/workflows/R-CMD-check.yaml

**Comment by jonjunduan** [comment]
The badge link on the README.md is not working. 

https://github.com/bcgov/bcdata/actions/workflows/R-CMD-check.yaml or https://github.com/bcgov/bcgovr/actions does not show the action results. 

The https://github.com/bcgov/bcdata/actions/workflows/R-CMD-check.yaml seems to be working. 
It does have a schedule: 
```
  schedule:
    - cron: '30 4 * * 1'
```

in the https://github.com/bcgov/bcdata/blob/main/.github/workflows/R-CMD-check.yaml #

**Comment by stephhazlitt** [comment]
> Hmm... is this not working currently? https://github.com/bcgov/bcgovr/blob/master/.github/workflows/R-CMD-check.yaml

Oof, I just clicked on the not working README badge and assumed. Updated the issue 😳

**Comment by jonjunduan** [comment]
When  `R-CMD-check.yaml` is triggered in GitHub action, it fails in `MacOS`, and has some deprecated steps. We may update it with new examples from R: https://github.com/r-lib/actions/blob/v2/examples/pkgdown.yaml

**Comment by ateucher** [comment]
@stephhazlitt if you call `usethis::use_github_action_check_standard()` and let it do its thing, it should overwrite what's there and setup an action that "just works".

**Comment by stephhazlitt** [comment]
Thanks @ateucher!
