### ISSUE TITLE
data licenses

### ISSUE THREAD

**Issue by MonkmanMH** [bcgov/bcgovr#9]
It would be handy if data licenses were added as options (and not necessarily mutually exclusive options, at that).  Particular favourites are 

* the [BC Government open license](http://www2.gov.bc.ca/gov/content/data/open-data/open-government-license-bc) 

* [Statistics Canada open license](http://www.statcan.gc.ca/eng/reference/licence)

**Comment by stephhazlitt** [comment]
A nice feature suggestion @MonkmanMH. At this time there is get_data_licence() in the [`envreportutils` package](https://github.com/bcgov/envreportutils) for adding urls to both of those examples (but not the LICENSE file itself). Perhaps we could add to that one and import it to `bcgovr`?

**Comment by ateucher** [comment]
@MonkmanMH do you a mean a LICENSE file for each of those licenses that you would put in a data folder?

**Comment by stephhazlitt** [comment]
@MonkmanMH Did you have a chance to look at `envreportutils::get_data_licence`? It returns a url, or a markdown or html-formatted link to one of several B.C. or Canadian licences:
- ogl-bc Open Government Licence - British Columbia
- bc-crown B.C. Crown Copyright
- ogl-canada Open Government Licence - Canada
- statscan Statistics Canada Open Licence Agreement

**Comment by ateucher** [comment]
After some discussion, we're not going to add the ability to add the data licenses as it is too easy to get wrong. I.e., for a user not experienced with how the OGL-BC works, it would be easy to just add the license to their repo that contains data, without having gone through the open data checklist and making sure there is a corresponding record in the BC Data Catalogue (as required by the license). We will add some documentation about how to deal with data licenses.
